spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://ec2-15-207-114-92.ap-south-1.compute.amazonaws.com:6603
    username: microserv
    password: testmicroserv
    testOnBorrow: true
    validationQuery: SELECT 1
    max-lifetime: 30000
  application:
    name: micro-dbserv
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true
